# Generated by Django 4.0.4 on 2022-05-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsa_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loglikelihood', models.JSONField()),
            ],
        ),
    ]
